local t = require('harness')
local config = require('nvime.config')

local describe, it, eq = t.describe, t.it, t.eq

describe('config.setup', function()
  it('returns the defaults when given nothing', function()
    local opts = config.setup(nil)
    eq(80, opts.panel.width)
    eq(false, opts.keymaps.enabled)
    eq('node', opts.agent.node)
  end)

  it('merges nested tables rather than replacing them', function()
    local opts = config.setup({ panel = { width = 120 } })
    eq(120, opts.panel.width)
    eq(3, opts.panel.prompt_height, 'untouched keys keep their default')
  end)

  it('is the single source of truth for the live options', function()
    config.setup({ panel = { width = 55 } })
    eq(55, config.get().panel.width)
  end)

  it('rejects out-of-range and wrongly-typed options', function()
    t.throws(function()
      config.setup({ panel = { width = 5 } })
    end, 'panel.width')
    t.throws(function()
      config.setup({ panel = { position = 'above' } })
    end, 'panel.position')
    t.throws(function()
      config.setup({ keymaps = { enabled = 'yes' } })
    end, 'keymaps.enabled')
    t.throws(function()
      config.setup({ context = { max_file_bytes = 10 } })
    end, 'max_file_bytes')
    t.throws(function()
      config.setup({ agent = { request_timeout_ms = 10 } })
    end, 'request_timeout_ms')
    t.throws(function()
      config.setup('nope')
    end, 'expected a table')
  end)

  it('leaves the previous options in place when validation fails', function()
    config.setup({ panel = { width = 90 } })
    pcall(config.setup, { panel = { width = -1 } })
    eq(90, config.get().panel.width)
  end)
end)
