local t = require('harness')
local config = require('nvime.config')
local context = require('nvime.context')

local describe, it, eq, ok = t.describe, t.it, t.eq, t.ok

local function sandbox()
  local dir = vim.fs.normalize(vim.fn.tempname())
  vim.fn.mkdir(dir .. '/sub', 'p')
  vim.fn.writefile({ 'local a = 1', 'return a' }, dir .. '/a.lua')
  vim.fn.writefile({ 'b' }, dir .. '/sub/b.txt')
  return dir
end

--- Every case passes an explicit root, exactly as `chat.lua` does.
local function expand(prompt, root)
  return context.expand(prompt, root or vim.uv.cwd())
end

describe('context.expand', function()
  it('attaches a referenced file', function()
    config.setup({})
    local dir = sandbox()
    local blocks, warnings = expand('explain @' .. dir .. '/a.lua please')
    eq({}, warnings)
    eq(1, #blocks)
    eq('file', blocks[1].type)
    eq('local a = 1\nreturn a', blocks[1].text)
    vim.fn.delete(dir, 'rf')
  end)

  it('attaches a directory as a bounded listing, not its contents', function()
    config.setup({})
    local dir = sandbox()
    local blocks = expand('what is in @' .. dir)
    eq(1, #blocks)
    eq('dir', blocks[1].type)
    ok(vim.tbl_contains(blocks[1].entries, 'a.lua'), 'the listing names the files')
    ok(blocks[1].text == nil, 'a directory block carries no file text')
    vim.fn.delete(dir, 'rf')
  end)

  it('attaches each path once, however often it is written', function()
    config.setup({})
    local dir = sandbox()
    local blocks = expand('@' .. dir .. '/a.lua and again @' .. dir .. '/a.lua')
    eq(1, #blocks)
    vim.fn.delete(dir, 'rf')
  end)

  it('warns instead of silently skipping a path that does not exist', function()
    config.setup({})
    local blocks, warnings = expand('look at @/definitely/not/here.lua')
    eq({}, blocks)
    eq(1, #warnings)
    ok(warnings[1]:find('did not resolve') ~= nil)
  end)

  it('refuses a file over the size limit and says so', function()
    config.setup({ context = { max_file_bytes = 1024 } })
    local dir = sandbox()
    local big = dir .. '/big.txt'
    vim.fn.writefile({ string.rep('x', 4096) }, big)
    local blocks, warnings = expand('@' .. big)
    eq({}, blocks)
    eq(1, #warnings)
    ok(warnings[1]:find('over the') ~= nil)
    vim.fn.delete(dir, 'rf')
  end)

  it('caps how many entries a directory contributes', function()
    config.setup({ context = { max_dir_entries = 2 } })
    local dir = sandbox()
    for i = 1, 10 do
      vim.fn.writefile({ 'x' }, string.format('%s/f%d.txt', dir, i))
    end
    local blocks = expand('@' .. dir)
    eq(2, #blocks[1].entries)
    vim.fn.delete(dir, 'rf')
  end)

  it('does not mistake an email address for a reference', function()
    config.setup({})
    local blocks, warnings = expand('mail someone@example.com about it')
    eq({}, warnings)
    eq({}, blocks)
  end)

  it('resolves a relative path against the given root, not the editor cwd', function()
    config.setup({})
    local dir = sandbox()
    local before = vim.uv.cwd()
    vim.cmd('cd ' .. vim.fn.fnameescape(vim.fs.dirname(dir)))
    local blocks, warnings = context.expand('explain @a.lua', dir)
    vim.cmd('cd ' .. vim.fn.fnameescape(before))
    eq({}, warnings)
    eq(1, #blocks)
    eq(dir .. '/a.lua', blocks[1].path)
    vim.fn.delete(dir, 'rf')
  end)

  it('refuses to guess a root instead of being told one', function()
    config.setup({})
    t.throws(function()
      context.expand('@a.lua')
    end, 'absolute root')
    t.throws(function()
      context.expand('@a.lua', 'relative/dir')
    end, 'absolute root')
  end)

  it('rejects a binary file rather than shipping mojibake', function()
    config.setup({})
    local dir = sandbox()
    local blob = dir .. '/logo.png'
    local handle = assert(io.open(blob, 'wb'))
    -- readfile() turns every NUL into a newline, so the check must read bytes.
    handle:write('\137PNG\r\n\026\n\0\0\0\13IHDR\255\254\253')
    handle:close()
    local blocks, warnings = expand('@' .. blob, dir)
    eq({}, blocks)
    eq(1, #warnings)
    ok(warnings[1]:find('looks binary') ~= nil, 'got: ' .. tostring(warnings[1]))
    vim.fn.delete(dir, 'rf')
  end)

  it('keeps a text file byte-faithful, minus its trailing newline', function()
    config.setup({})
    local dir = sandbox()
    local path = dir .. '/crlf.txt'
    local handle = assert(io.open(path, 'wb'))
    handle:write('one\r\ntwo\n')
    handle:close()
    local blocks = expand('@' .. path, dir)
    eq('one\r\ntwo', blocks[1].text)
    vim.fn.delete(dir, 'rf')
  end)
end)

describe('context.project_root', function()
  it('is an absolute directory', function()
    local root = context.project_root()
    ok(vim.startswith(root, '/'), 'the root must be absolute')
    ok(vim.uv.fs_stat(root).type == 'directory')
  end)
end)
